name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        dockerfile: [ 'frank', 'node', 'php-cli' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./${{ matrix.dockerfile }}Dockerfile
          push: true
          tags: ${{ matrix.php }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            FRANK_VERSION=1.4.4
            NODE_VERSION=22.11.0

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/my-docker-hub-namespace/my-docker-hub-repository
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
