name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        node: [ 22.11.0 ]
        frank: [ 1.5.0 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: make PHP_VERSION=${{ matrix.php }} NODE_VERSION=${{ matrix.node }} FRANK_VERSION=${{ matrix.frank }} push
